In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
# @title Import necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
# @title Load the dataset 'Buy_computers.csv' into a Pandas DataFrame

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Buy_Computer.csv')


In [9]:
print(df)

    id         age  income  student  credit_rating Buy_Computer
0    1       youth       0        0              1           no
1    2       youth       0        0              0           no
2    3  middle_age       0        0              1          yes
3    4      senior       2        0              1          yes
4    5      senior       1        1              1          yes
5    6      senior       1        1              0           no
6    7  middle_age       1        1              0          yes
7    8       youth       2        0              1           no
8    9       youth       1        1              1          yes
9   10      senior       2        1              1          yes
10  11       youth       2        1              0          yes
11  12  middle_age       2        0              0          yes
12  13  middle_age       0        1              1          yes
13  14      senior       2        0              0           no


In [10]:
from sklearn.preprocessing import LabelEncoder
comp_data_num = df.apply(LabelEncoder().fit_transform)
data = np.array(comp_data_num.iloc[:, 1:5])
target = np.array(comp_data_num.iloc[:, 5])

In [11]:
print(data)

[[2 0 0 1]
 [2 0 0 0]
 [0 0 0 1]
 [1 2 0 1]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 0]
 [2 2 0 1]
 [2 1 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 0 1 1]
 [1 2 0 0]]


In [12]:
print(target)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [13]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(data, target)

SVC(kernel='linear', random_state=0)

In [14]:
test_data = {
    'id':[11],
    'age':[27],
    'income':['high'],
    'student':['no'],
    'credit_rating':['excellent']}

In [15]:
test_df = pd.DataFrame(test_data)

In [16]:
test_df = test_df.apply(LabelEncoder().fit_transform)

In [17]:
testdata = np.array(test_df.iloc[:, 1:5])

In [19]:
print(classifier.predict(testdata))

[1]


In [23]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

# Load the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Buy_Computer.csv')

# Preprocess the data
comp_data_num = dataset.apply(LabelEncoder().fit_transform)
data = np.array(comp_data_num.iloc[:, 1:5])
target = np.array(comp_data_num.iloc[:, 5])

# Train the SVM model
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(data, target)

# Create new data to predict on
test_data = {
    'id': [11],
    'age': [27],
    'income': ['high'],
    'student': ['no'],
    'credit_rating': ['excellent']
}

# Load test data into a DataFrame object
test_df = pd.DataFrame(test_data)
test_df = test_df.apply(LabelEncoder().fit_transform)
testdata = np.array(test_df.iloc[:, 1:5])

# Predict using the trained model
prediction = classifier.predict(testdata)

# Output the prediction
if prediction[0] == 1:
    print("Yes")
else:
    print("No")


Yes
