Support Vector Machine (SVM) Excercise

Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [5]:
dataset = pd.read_csv('Buy_Computer.csv')


In [6]:
print(dataset)

    id         age  income student credit_rating Buy_Computer
0    1       youth    high      no          fair           no
1    2       youth    high      no     excellent           no
2    3  middle_age    high      no          fair          yes
3    4      senior  medium      no          fair          yes
4    5      senior     low     yes          fair          yes
5    6      senior     low     yes     excellent           no
6    7  middle_age     low     yes     excellent          yes
7    8       youth  medium      no          fair           no
8    9       youth     low     yes          fair          yes
9   10      senior  medium     yes          fair          yes
10  11       youth  medium     yes     excellent          yes
11  12  middle_age  medium      no     excellent          yes
12  13  middle_age    high     yes          fair          yes
13  14      senior  medium      no     excellent           no


Feature Scaling

In [7]:
from sklearn.preprocessing import LabelEncoder
comp_data_num = dataset.apply(LabelEncoder().fit_transform)
data = np.array(comp_data_num.iloc[:, 1:5])
target = np.array(comp_data_num.iloc[:, 5])

In [8]:
print(data)

[[2 0 0 1]
 [2 0 0 0]
 [0 0 0 1]
 [1 2 0 1]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 0]
 [2 2 0 1]
 [2 1 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 0 1 1]
 [1 2 0 0]]


Training the SVM model on the data set

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(data, target)

SVC(kernel='linear', random_state=0)

Creating new data to predict on

In [10]:
test_data = {
    'id':[11],
    'age':[27],
    'income':['high'],
    'student':['no'],
    'credit_rating':['excellent']}



In [11]:
#load test data into a DataFrame object:
test_df = pd.DataFrame(test_data)

In [14]:
test_df = test_df.apply(LabelEncoder().fit_transform)


In [16]:
testdata = np.array(test_df.iloc[:, 1:5])

In [17]:
print(classifier.predict(testdata))

[1]
